AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - db/schema.rb
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - bin/*

### Bundler

Bundler/OrderedGems:
  Enabled: false


### Metrics

Metrics/AbcSize:
  Max: 20
  Exclude:
    -

Metrics/BlockLength:
  Max: 150

Metrics/LineLength:
  Max: 140

Metrics/MethodLength:
  Max: 15
  Exclude:
    -


### Style

Style/AutoResourceCleanup:
  Enabled: true

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/Encoding:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ImplicitRuntimeError:
  Enabled: true

Style/RegexpLiteral:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: true

Style/StringLiterals:
  Enabled: false

Style/StringMethods:
  Enabled: true

Style/SymbolArray:
  EnforcedStyle: brackets

Style/MixinUsage:
  Enabled: false

Style/StderrPuts:
  Enabled: false


### Lint

Lint/MissingCopEnableDirective:
  Enabled: false


### Layout

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/FirstArrayElementLineBreak:
  Enabled: true

Layout/FirstHashElementLineBreak:
  Enabled: true

Layout/FirstMethodArgumentLineBreak:
  Enabled: true

Layout/FirstMethodParameterLineBreak:
  Enabled: true

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Layout/HashAlignment:
  Enabled: false


### Documentation

Style/Documentation:
  Enabled: false
